name: Docker Build
on: [push]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build images
      run: |
        echo "[*] Building for tag '$IMAGE_TAG'"
        echo "[+] sqlite3"
        docker build . --file Dockerfile --tag r4mmer/django-gunicorn-nginx:$IMAGE_TAG
        docker tag r4mmer/django-gunicorn-nginx:$IMAGE_TAG r4mmer/django-gunicorn-nginx:latest

        echo "[+] Postgres"
        docker build . --file pg.Dockerfile --tag r4mmer/django-gunicorn-nginx:$IMAGE_TAG-postgres
        docker tag r4mmer/django-gunicorn-nginx:$IMAGE_TAG-postgres r4mmer/django-gunicorn-nginx:latest-postgres

        echo "[+] MySQL"
        docker build . --file mysql.Dockerfile --tag r4mmer/django-gunicorn-nginx:$IMAGE_TAG-mysql
        docker tag r4mmer/django-gunicorn-nginx:$IMAGE_TAG-mysql   r4mmer/django-gunicorn-nginx:latest-mysql
    - name: Push images
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      run: |
        echo "[*] Login and push images"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        docker push r4mmer/django-gunicorn-nginx:$IMAGE_TAG
        docker push r4mmer/django-gunicorn-nginx:latest
        docker push r4mmer/django-gunicorn-nginx:$IMAGE_TAG-postgres
        docker push r4mmer/django-gunicorn-nginx:latest-postgres
        docker push r4mmer/django-gunicorn-nginx:$IMAGE_TAG-mysql
        docker push r4mmer/django-gunicorn-nginx:latest-mysql
